name: absensi
description: "A product for record attendance employee for company HR/HC management system"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.5.3

dependencies:
  carousel_slider: ^5.0.0
  date_picker_plus: ^4.1.0
  dio: ^5.7.0
  http: ^1.2.2
  shared_preferences: ^2.3.3
  flutter:
    sdk: flutter
  geolocator: ^13.0.1
  get: ^4.6.6
  google_fonts: ^6.2.1
  intl: ^0.19.0
  package_info_plus: ^8.1.0
  syncfusion_flutter_datepicker: ^27.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo/logo_primary.png
    - assets/images/hello/onboard1.png
    - assets/images/hello/onboard2.png
    - assets/images/hello/onboard3.png
    - assets/icons/system/avatar.png
    - assets/icons/system/clock_in.png
    - assets/icons/system/clock_out.png
    - assets/icons/system/clock_time.png
    - assets/icons/system/bell.png
    - assets/icons/system/bell_fill.png
    - assets/icons/system/calendar_line.png
    - assets/icons/system/filter.png
    - assets/icons/system/Briefcase.png
    - assets/icons/system/Briefcase_fill.png
    - assets/icons/system/list.png
    - assets/icons/system/lock_fill.png
    - assets/icons/system/lock.png
    - assets/icons/system/search.png
    - assets/icons/system/shield.png
    - assets/icons/system/trash.png
    - assets/icons/system/folder.png
    - assets/icons/system/usercomunity.png
    - assets/icons/menus/Calendar.png
    - assets/icons/menus/Documents.png
    - assets/icons/menus/Form.png
    - assets/icons/menus/Holiday.png
    - assets/icons/menus/PurchaseOrder.png
    - assets/icons/menus/SystemReport.png
    - assets/icons/menus/Timer.png
    - assets/icons/menus/Training.png
    - assets/icons/navbar/calendar_fill.png
    - assets/icons/navbar/home_fill.png
    - assets/icons/navbar/inbox_fill.png
    - assets/icons/navbar/usergroup_fill.png
    - assets/icons/navbar/profil_fill.png
    - assets/icons/navbar/calendar.png
    - assets/icons/navbar/home.png
    - assets/icons/navbar/inbox.png
    - assets/icons/navbar/usergroup.png
    - assets/icons/navbar/profil.png

