name: absensi
description: "A product for record attendance employee for company HR/HC management system"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.5.3

dependencies:
  carousel_slider: ^5.0.0
  date_picker_plus: ^4.1.0
  http: ^1.2.2
  flutter:
    sdk: flutter
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  get: ^4.6.6
  google_fonts: ^6.2.1
  intl: ^0.19.0
  package_info_plus: ^8.1.0
  syncfusion_flutter_datepicker: ^27.2.2
  sqflite: ^2.4.1
  path: ^1.9.0
  flutter_profile_picture: ^2.0.0
  shared_preferences: ^2.3.3
  shimmer: ^3.0.0
  statusbarz: ^1.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo/
    - assets/images/hello/
    - assets/icons/system/
    - assets/icons/menus/
    - assets/icons/navbar/

